=== JOUINISofiene/test/src/javaapplication2/annuaire.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT annuaire (personne)*>


<!ELEMENT personne (nom,prenom,email*)>

<!ATTLIST personne
    type CDATA #REQUIRED
  >


<!ELEMENT nom (#PCDATA)>

<!ELEMENT prenom (#PCDATA)>

<!ELEMENT email (#PCDATA)>

=== JOUINISofiene/test/src/javaapplication2/annuaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE annuaire SYSTEM "annuaire.dtd">

<annuaire>
    <personne type="Ã©tudiant">
        <nom>Alain</nom> 
        <prenom>Bob</prenom>
        <email>bob@yahou.fr</email>
        
    </personne >
    <personne type="technicien">
        <nom>Alain</nom> 
        <prenom>Alice</prenom>
        <email>alice@gmail.com</email>
        
        
    </personne>   
</annuaire>
