=== JOUINISofiene/test/src/javaapplication2/livre2.dtd
<?xml version='1.0' encoding='UTF-8'?>


<!ELEMENT livre (section,section+,auteur*)>
<!ELEMENT section (chapitre,chapitre+)>
<!ELEMENT chapitre (paragraphe,paragraphe+)>
<!ELEMENT paragraphe (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ATTLIST auteur nom CDATA #REQUIRED >
<!ATTLIST auteur prenom CDATA #REQUIRED>
<!ATTLIST livre titre CDATA #REQUIRED>
<!ATTLIST section titre CDATA #REQUIRED>
<!ATTLIST chapitre titre CDATA #REQUIRED>

=== JOUINISofiene/test/src/javaapplication2/livre2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE livre SYSTEM "livre2.dtd"> 
<livre titre="Les miserables">
    <section titre="sec1">
        <chapitre titre="chap1">
            <paragraphe>sec 1 chap1 paragraphe1</paragraphe>
            <paragraphe>sec 1 chap1 paragraphe2</paragraphe>
        </chapitre>
        <chapitre titre="chap2"> 
        <paragraphe>sec 1 chap2 paragraphe1</paragraphe>
        <paragraphe>sec1 chap2 paragraphe2</paragraphe>
        </chapitre>
    </section> 
    <section titre="sec2">
        <chapitre titre="chap1"> 
        <paragraphe>sec 2 chap1 paragraphe1</paragraphe>
        <paragraphe>sec 2 chap1 paragraphe2</paragraphe>
        </chapitre>
        <chapitre titre="chap2"> 
        <paragraphe>sec 2 chap2 paragraphe1</paragraphe>
        <paragraphe>sec 2 chap2 paragraphe2</paragraphe>
        
        
        </chapitre> 
        
        
    </section>
    <auteur nom="Hugo" prenom="Vector"/>
       
        
    
          <auteur nom="Camus" prenom="Albert"/>
        
        
    
</livre>
